apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: rcc-api-test
  name: rcc-api-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rcc-api-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

    
  template:
    metadata:
      labels:
        app: rcc-api-test
    spec:
      containers:
          image: 'registry-vpc.cn-hangzhou.aliyuncs.com/rcc/rcc_api_test:IMAGE_TAG'
          imagePullPolicy: Always
          name: rcc-api-test
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: pro
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
