# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: call.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='call.proto',
  package='callpb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\ncall.proto\x12\x06\x63\x61llpb\"#\n\x03Req\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0e\n\x06params\x18\x02 \x01(\t\"3\n\x04Resp\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x32*\n\x03Srv\x12#\n\x04\x43\x61ll\x12\x0b.callpb.Req\x1a\x0c.callpb.Resp\"\x00\x62\x06proto3'
)




_REQ = _descriptor.Descriptor(
  name='Req',
  full_name='callpb.Req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='callpb.Req.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='callpb.Req.params', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=57,
)


_RESP = _descriptor.Descriptor(
  name='Resp',
  full_name='callpb.Resp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='callpb.Resp.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='callpb.Resp.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='callpb.Resp.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['Req'] = _REQ
DESCRIPTOR.message_types_by_name['Resp'] = _RESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Req = _reflection.GeneratedProtocolMessageType('Req', (_message.Message,), {
  'DESCRIPTOR' : _REQ,
  '__module__' : 'call_pb2'
  # @@protoc_insertion_point(class_scope:callpb.Req)
  })
_sym_db.RegisterMessage(Req)

Resp = _reflection.GeneratedProtocolMessageType('Resp', (_message.Message,), {
  'DESCRIPTOR' : _RESP,
  '__module__' : 'call_pb2'
  # @@protoc_insertion_point(class_scope:callpb.Resp)
  })
_sym_db.RegisterMessage(Resp)



_SRV = _descriptor.ServiceDescriptor(
  name='Srv',
  full_name='callpb.Srv',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=112,
  serialized_end=154,
  methods=[
  _descriptor.MethodDescriptor(
    name='Call',
    full_name='callpb.Srv.Call',
    index=0,
    containing_service=None,
    input_type=_REQ,
    output_type=_RESP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SRV)

DESCRIPTOR.services_by_name['Srv'] = _SRV

# @@protoc_insertion_point(module_scope)
