# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import util.grpctools.call_pb2 as call__pb2


class SrvStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Call = channel.unary_unary(
        '/callpb.Srv/Call',
        request_serializer=call__pb2.Req.SerializeToString,
        response_deserializer=call__pb2.Resp.FromString,
        )


class SrvServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Call(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SrvServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Call': grpc.unary_unary_rpc_method_handler(
          servicer.Call,
          request_deserializer=call__pb2.Req.FromString,
          response_serializer=call__pb2.Resp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'callpb.Srv', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
